### ISSUE TITLE
not enough values to unpack(expected 3,got 1)

### ISSUE THREAD

**Issue by xueluna** [afortunado-aceptado/Rudra#1]
When running the code,it met problem : in Rudra\main\run.py,line 103,in jumpover_condition
[contest,_,_]=dir_info.split(os.sep)
ValueError:not enough values to unpacked(expected 3,got 1)

**Comment by 2ira** [comment]
Maybe the operating system is different, os.sep is a constant that represents the character used to separate components in a file path for the current operating system. It is typically '/' on Unix and Linux systems, and '' on Windows systems. When defining sep = '/' to expect a Unix/Linux-style path separator, it creates a hardcoded separator that may not match the behavior of native path-handling functions if run on a different OS.You can check your version，print your split component and modify to fix it.

**Comment by xueluna** [comment]
> Maybe the operating system is different, os.sep is a constant that represents the character used to separate components in a file path for the current operating system. It is typically '/' on Unix and Linux systems, and '' on Windows systems. When defining sep = '/' to expect a Unix/Linux-style path separator, it creates a hardcoded separator that may not match the behavior of native path-handling functions if run on a different OS.You can check your version，print your split component and modify to fix it.

Thanks,the issue has been solved.
